### ISSUE TITLE
`osx osx_64_numpy1.21python3.10.____cpython` Azure pipelines failed

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/ipykernel-feedstock#116]
Hi,

the `osx osx_64_numpy1.21python3.10.____cpython` run for the last upload failed. Could that be restarted please, thanks!

Ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=460147&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73

**Comment by bollwyvl** [comment]
Kicked it:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=460147&view=logs&j=1895d41f-00e9-50af-3b2f-0556baeaa32d

**Comment by BastianZim** [comment]
Thanks!

**Comment by BastianZim** [comment]
Worked. Thanks!

**Comment by bollwyvl** [comment]
it's up: please re-open if there are further issues (beyond CDN delay :crying_cat_face: )
