### ISSUE TITLE
Problems with explicit import

### ISSUE THREAD

**Issue by darribas** [conda-forge/ipykernel-feedstock#13]
I'm trying to test Windows for a setup using explicit links. Since I don't have access to a Windows machine at the moment, I set up an environment with a `.yml` that passed my tests and I printed the explicit list, then using that for the same tests. The setup is available to look here:

https://github.com/darribas/gds_env/blob/master/appveyor.yml

Appveyor fails apparently on `conda-forge::ipykernel`:

https://ci.appveyor.com/project/darribas/gds-env/build/job/xcs438v02hd1jid6

Any idea what that link error means? Any suggestion/help would be most appreciated. Thank you very much!

**Comment by ocefpaf** [comment]
@darribas can you copy and paste the error here? I cannot see the AppVeyor log.

**Comment by jakirkham** [comment]
I think this is the [log]( https://ci.appveyor.com/project/darribas/gds-env/build/job/19b6oc74twgyv2tu ) being referred to. Though it doesn't give much to go off of. Snippet below.

```
Linking packages ...
[affine              ]|                               LinkError: Link error: Error: post-link failed for: conda-forge::ipykernel-4.5.0-py27_0 
```

However, this may be a red herring as the other [build]( https://ci.appveyor.com/project/darribas/gds-env/build/job/kgfpe9u45k35nggu ) in that matrix fails due to the placeholder length.

```
Linking packages ...
[freexl              ]|#########                                      PaddingError: Placeholder of length '20' too short in package conda-forge::hdf5-1.8.17-vc9_4.
The package must be rebuilt with conda-build > 2.0.
Command exited with code 1
```

**Comment by darribas** [comment]
Yes, that was the error @jakirkham , thanks for pasting. It should reproduce with this file of explicit links:

https://github.com/darribas/gds_env/blob/master/gds_requirements_win-64.txt

which I obtained from printing on the screen `conda list --explicit` from the Appveyor log.

**Comment by ocefpaf** [comment]
@darribas closing this as stale. I guess it was fixed at some point. Sorry for losing track of it.
