### ISSUE TITLE
No __osx package generated for ipykernel 6.24

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/ipykernel-feedstock#166]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Looking at https://anaconda.org/conda-forge/ipykernel/files, I see that only two variants of the 6.24 package were built: `__win` and `__linux`, but no `__osx` package was built. Notice that 6.23.3 has three variants built. 6.24 was built 3 days ago - perhaps this is a delay in building osx packages?

The effect is that I cannot install ipykernel 6.24 on a mac m1 with micromamba using conda-forge

```
$ micromamba create -n ipykernel ipykernel=6.24
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    └─ ipykernel 6.24**  is not installable because there are no viable options
       ├─ ipykernel 6.24.0 would require
       │  └─ __win, which is missing on the system;
       └─ ipykernel 6.24.0 would require
          └─ __linux, which is missing on the system.
critical libmamba Could not solve for environment specs
```

### Installed packages

```shell
Clean environment
```

### Environment info

```shell
$ micromamba info

       libmamba version : 1.4.7
     micromamba version : 1.4.7
           curl version : libcurl/7.88.1 SecureTransport (OpenSSL/3.1.1) zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
[snip]
       virtual packages : __unix=0=0
                          __osx=13.4.1=0
                          __archspec=1=arm64
               channels : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
[snip]
               platform : osx-arm64
```

**Comment by jasongrout** [comment]
I also [asked in conda-forge chat](https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$16887351842Zlixl:gitter.im?via=matrix.org&via=gitter.im&via=cadair.com) about this.

**Comment by bollwyvl** [comment]
Thanks, have re-kicked the build, and will monitor:

https://github.com/conda-forge/ipykernel-feedstock/runs/14746045228

**Comment by bollwyvl** [comment]
Now seeing [3](https://anaconda.org/conda-forge/ipykernel/files?version=6.24.0), with the latest one [described as](https://anaconda.org/conda-forge/ipykernel/files/modal/info/64a8208240947d77863d85a0). Please reopen if any lingering issues persist :P
