### ISSUE TITLE
win-32 ipykernel-4.6.1-py35_0.tar.bz2 should not include `Lib/site-packages/__pycache__/six.cpython-35.pyc`

### ISSUE THREAD

**Issue by cfobel** [conda-forge/ipykernel-feedstock#21]
The [Windows 32-bit][win32] and [64-bit][win64] `ipykernel-4.6.1-py35_0.tar.bz2` Conda package available from the `conda-forge` channel include the following file (though they shouldn't):

    Lib/site-packages/__pycache__/six.cpython-35.pyc

Note that the above file is (correctly) **not** included in the Python 3.6 release, i.e., `ipykernel-4.6.1-py36_0.tar.bz2`.

# Implications

This file is included in the `six` package and causes, for example, the following duplicate file errors when building a Miniconda installer using `constructor`:

    Error: File 'Lib/site-packages/__pycache__/six.cpython-35.pyc' found in multiple packages: ipykernel-4.6.1-py35_0.tar.bz2, six-1.10.0-py35_1.tar.bz2

[win32]: https://anaconda.org/conda-forge/ipykernel/4.6.1/download/win-32/ipykernel-4.6.1-py35_0.tar.bz2
[win64]: https://anaconda.org/conda-forge/ipykernel/4.6.1/download/win-64/ipykernel-4.6.1-py35_0.tar.bz2

**Comment by minrk** [comment]
This is fixed in the 4.7 packages
