### ISSUE TITLE
Issue with ipykernel-4.8.2-py35_0

### ISSUE THREAD

**Issue by patman77** [conda-forge/ipykernel-feedstock#26]
Hello everyone,

I have a question: I'm currently doing the Udacity Self Driving Car Engineer nanodegree program.

To solve the tasks, an environment is built up, based on an yml file with the content:

name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - pip:
        - moviepy
        - tensorflow==0.12.1
        - keras==1.2.1

When I activate via "conda env create -f environment.yml", I get back the following error:

ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'conda-forge::ipykernel-4.8.2-py35_0'.
LinkError: Link error: Error: post-link failed for: conda-forge::ipykernel-4.8.2-py35_0

This happens on Windows 10. The very same file works on Mac OS X. Any ideas, anyone, how to solve this?

Thanks, Patrick

**Comment by ocefpaf** [comment]
I could not reproduce this. Either it was fixed or it was a transient error. Please re-open if you are still experiencing this.
