### ISSUE TITLE
conda-forge ipykernel-5.1.0-pyh24bf2e0_0 is broken for Windows users

### ISSUE THREAD

**Issue by rs2** [conda-forge/ipykernel-feedstock#37]
### Symptoms
KernelError in Jupyter Notebooks running on win-64 architecture.
![image](https://user-images.githubusercontent.com/4407787/48199050-ca8f1c00-e352-11e8-8832-6f59f47b2ed7.png)

### Problem
`ipykernel-5.1.0` is being classified as `noarch` in `conda-forge`. As such, the tarball is missing `.ipykernel-post-link.bat` that is important for `win-64` platforms: it fixes the path in `kernels/python3/kernel.json`.

NB: `ipykernel-5.1.0` is correctly classified as architecture-dependent in the `defaults` anaconda channel.

### Compare:
* `win-64`-compatible [`ipykernel-5.1.0` in defaults channel](https://anaconda.org/anaconda/ipykernel/5.1.0/download/win-64/ipykernel-5.1.0-py36h39e3cac_0.tar.bz2).
* `noarch` [`ipykernel-5.1.0` in conda-forge](https://anaconda.org/conda-forge/ipykernel/5.1.0/download/noarch/ipykernel-5.1.0-pyh24bf2e0_0.tar.bz2).

@blink1073, @hmaarrfk What was the rationale behind marking `ipykernel` as `noarch` in https://github.com/conda-forge/ipykernel-feedstock/commit/227b6cc37689fb9e116f4dfecf0036ab5c018811 (https://github.com/conda-forge/ipykernel-feedstock/pull/34)?

**Comment by hmaarrfk** [comment]
I've been having these issues too. I guess I didn't test it thoroughly enough. I guess we should revert those commits?

**Comment by bollwyvl** [comment]
Hm, the kernel spec is now put in place at build time, rather than post,
so maybe the path is ending up with bad slashes. However, the argv might
not be correctly escaped. Trouble with json.

Can you provide the kernel.json file you are seeing after a 'conda create
-n test IPython=7'?

**Comment by hmaarrfk** [comment]
@rs2 the comment in the file states that the post unlink script used to be included because conda didn't parse json files: https://github.com/conda-forge/ipykernel-feedstock/pull/33/files#diff-9281e96d80111563776ada67648cc668

apparently they upgraded their system and it *should* have worked.

**Comment by hmaarrfk** [comment]
```json
{
 "argv": [
  "C:/Users/mark/Miniconda3/envs/temp/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

I guess the slashes are wrong. I think we just need to remove the noarch right, but don't need the postlink script?

**Comment by rs2** [comment]
@hmaarrfk You may find that there's no `bin/` under `C:/Users/mark/Miniconda3/envs/temp`.

**Comment by rs2** [comment]
@hmaarrfk `share/jupyter/kernels/python3/kernel.json` in https://anaconda.org/conda-forge/ipykernel/5.1.0/download/noarch/ipykernel-5.1.0-pyh24bf2e0_0.tar.bz2 contains `"/opt/anaconda1anaconda2anaconda3/bin/python"`, 
whereas https://anaconda.org/anaconda/ipykernel/5.1.0/download/win-64/ipykernel-5.1.0-py36h39e3cac_0.tar.bz2 has `"C:\\ci\\ipykernel_1539879631431\\_h_env\\python.exe"`.

**Comment by hmaarrfk** [comment]
interesting that there is no bin on windows. I guess I still had the old kernel spec when I was testing in my environment. Do you know how we would add a test to avoid this in the future?

**Comment by hmaarrfk** [comment]
i guess there was already a test there, it just has to stay arch dependent for a while. :/

**Comment by rs2** [comment]
After all, it maybe a `conda` issue. Search for `PrefixReplaceLinkAction` in https://github.com/conda/conda/issues/7505.

**Comment by hmaarrfk** [comment]
In either case, ipykernels is kinda broken and a huge bummer. We should find a workaround.

**Comment by hmaarrfk** [comment]
mine has been to delete the python kernels folder on my machine. it seems to get regenerated automatically :/

**Comment by rs2** [comment]
I think a (strong) rule of thumb should be that any conda recipe that makes use of [prefixes](https://github.com/conda-forge/ipykernel-feedstock/blob/master/recipe/meta.yaml#L16) should never be declared `noarch`.

**Comment by hmaarrfk** [comment]
Good point. Maybe I have to re-add https://github.com/conda-forge/ipykernel-feedstock/pull/33/files#diff-4549cc645c735cb12d844512ce880c2c

**Comment by minrk** [comment]
Good catch, folks. Let's go back to arch dependent, but keep the removal of the post-link script.

**Comment by bollwyvl** [comment]
Agreed. Probably have to skip the async tests on Windows...

**Comment by hmaarrfk** [comment]
Should the packages that I had identified in #39 be marked as broken?

**Comment by bollwyvl** [comment]
> Should the packages that I had identified in #39 be marked as broken?

Yes, they probably should, but they _aren't_ broken on OSX/Linux. I assume we have to go through Proper Channels to make that happen, as it seems a bit overpowered for the bot to do. Unfortunately burnt most of my discretionary FOSS time on getting these out, so we'll have to Keep Calm and Make an Issue

Py37 packages are up
https://anaconda.org/conda-forge/ipykernel/files?version=5.1.0

I tested a local env like this:
```yml
# environment.yml
name: winsmoke
channels:
- conda-forge
- nodefaults
dependencies:
- jupyterlab
- python=3.7
```

And everything looks correct on win/linux (don't have a mac):
- starting a kernel in lab
- using `nbconvert --execute`

**Comment by bollwyvl** [comment]
I think this is resolved!
