### ISSUE TITLE
Remove broken ipykernel-4.10.0 package?

### ISSUE THREAD

**Issue by croth1** [conda-forge/ipykernel-feedstock#64]
It seems that there are broken packages due to missing dependencies out in the wild:

## Steps to reproduce:
```
mamba create -n foo27  python=2.7 ipykernel
python -m ipykernel install
```
gives following error:
```
[...]
  File "/Users/christian/miniconda3/envs/foo27/lib/python2.7/site-packages/wcwidth/__init__.py", line 12, in <module>
    from .wcwidth import ZERO_WIDTH  # noqa
  File "/Users/christian/miniconda3/envs/foo27/lib/python2.7/site-packages/wcwidth/wcwidth.py", line 79, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

`conda list ipykernel --show-channel-urls`

```
ipykernel                 4.10.0                   py27_0    conda-forge
```

I know the time of python 2.7 is over, but I suggest we remove those broken builds to reduce friction for our users.

**Comment by croth1** [comment]
Oh, snap! That's an issue in `wcwidth`. Sorry for the noise.

**Comment by ocefpaf** [comment]
Bare in mind that we dropped support for Python 2 a while back, so there is no guarantee to ship noarch packages with extra dependencies just to fix this.
