### ISSUE TITLE
Restore pypy builds for 6.x

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/ipykernel-feedstock#85]
For now, it looks like we won't be able to have 6.x builds against pypy on unix due to some fairly basic lifecycle issues (kernels can't be stopped). So that we can start getting some of the good features, I've proposed skipping pypy/unix for `6.0.0_*_0` on #84.

Simultaneously, we're trying to land the novel windows pypy37 variant on #83 (still apparently blocked by some upstreams), and just don't have enough data to know whether it's going to work. I propose we:
- create a `5.x` branch from the current `master`
- add it to the abi flag, a la [ipython](https://github.com/conda-forge/ipython-feedstock/blob/master/conda-forge.yml#L6)
- get the bot to retarget the PR against `5.x`

Related:
- https://github.com/conda-forge/ipykernel-feedstock/pull/83
- https://github.com/conda-forge/ipykernel-feedstock/pull/84
  - https://github.com/ipython/ipykernel/pull/700
    - https://github.com/erdewit/nest_asyncio/pull/55
      - https://github.com/jupyter/jupyter_client/pull/663

**Comment by mattip** [comment]
> some fairly basic lifecycle issues (kernels can't be stopped)

Is there something I can do to help with this?

**Comment by bollwyvl** [comment]
> help with this?

I haven't had the chance to dig into those upstream PRs, but it needs to be solved deeper in the stack than just packaging.

**Comment by bollwyvl** [comment]
Closed by #104
