### ISSUE TITLE
the latest version requires `importlib-metadata <4`!

### ISSUE THREAD

**Issue by muh-hassani** [conda-forge/ipykernel-feedstock#94]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: I am currently having python3.7 installed, and I would like to install the latest ipykernel. Strangely, I see that it requires `importlib-metadata <4`. I wonder, if this limit can be removed?
ipykernel>6 is needed for us to use jupyterlab debugger extension!

<br/>

**Comment by bollwyvl** [comment]
Hopefully fixed within the next few hours with #95

**Comment by muh-hassani** [comment]
thanks a lot @bollwyvl.
